name: Trigger CodeRabbit Review

on:
  pull_request:
    types: [opened]

jobs:
  trigger-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Post @coderabbitai comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const body = (pr.body || '').toLowerCase();
            const comment = body.includes('@coderabbitai_ignore') ? '@coderabbitai ignore' : '@coderabbitai review';

            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number
            });

            const exists = comments.data.some(c => c.body.trim().toLowerCase() === comment);
            if (!exists) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: comment
              });
            }
