name: Trigger CodeRabbit Review

on:
  pull_request:
    types: [opened]

jobs:
  trigger-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Post appropriate @coderabbitai comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prBody = pr.body ? pr.body.toLowerCase() : '';
            const commentBody = prBody.includes('@coderabbitai_ignore')
              ? '@coderabbitai ignore'
              : '@coderabbitai review';

            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number
            });

            const alreadyCommented = comments.data.some(comment => comment.body.includes(commentBody));
            if (!alreadyCommented) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: commentBody
              });
            }
