name: Label PR review outcome

on:
  pull_request_review:
    types: [submitted]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Update label based on review state
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { review, pull_request: pr } = context.payload;
            const state = review.state.toLowerCase();
            const { owner, repo } = context.repo;
            const issue_number = pr.number;

            const labelMap = {
              approved: 'approved',
              changes_requested: 'changes-requested',
              commented: 'needs-review',
              pending: 'needs-review',
              dismissed: null
            };

            const newLabel = labelMap[state];
            const allLabels = ['approved', 'changes-requested', 'needs-review'];

            const existing = await github.rest.issues.listLabelsOnIssue({
              owner,
              repo,
              issue_number
            });

            const currentLabels = existing.data.map(l => l.name);

            const toRemove = allLabels.filter(label => currentLabels.includes(label));
            for (const label of toRemove) {
              await github.rest.issues.removeLabel({ owner, repo, issue_number, name: label });
            }

            if (newLabel && !currentLabels.includes(newLabel)) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: [newLabel]
              });
            }
